var Abdullah = prompt("Enter your name")
console.log(Abdullah)
var seven = prompt("Your class")
console.log("7")
var seven = prompt("Your School")
console.log("Saqib Public")
var seven = prompt("Your Teachers")
console.log("Sir Rizwan and Asad")
var seven = prompt("Your Product")
console.log("Garay Niclos bat")